image: "ruby:2.4"

before_script:
  - ruby -v                                   # Print out ruby version for debugging

stages:
  - build
  - test
  - deploy

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  GIT_STRATEGY: clone

build:
  stage: build
  script:
    - bundle install
    - bundle exec fastlane build
  artifacts:
    paths:
      - ./*.ipa
